// Code generated by internal/gen; DO NOT EDIT.

package attr

import "github.com/rrchelbi/markup"

// Accept returns the accept attribute.
func Accept(v string) markup.Attr { return markup.NewAttr("accept", v) }

// Alt returns the alt attribute.
func Alt(v string) markup.Attr { return markup.NewAttr("alt", v) }

// Autocomplete returns the autocomplete attribute.
func Autocomplete(v string) markup.Attr { return markup.NewAttr("autocomplete", v) }

// Charset returns the charset attribute.
func Charset(v string) markup.Attr { return markup.NewAttr("charset", v) }

// Cols returns the cols attribute.
func Cols(v string) markup.Attr { return markup.NewAttr("cols", v) }

// Colspan returns the colspan attribute.
func Colspan(v string) markup.Attr { return markup.NewAttr("colspan", v) }

// Content returns the content attribute.
func Content(v string) markup.Attr { return markup.NewAttr("content", v) }

// Crossorigin returns the crossorigin attribute.
func Crossorigin(v string) markup.Attr { return markup.NewAttr("crossorigin", v) }

// Dir returns the dir attribute.
func Dir(v string) markup.Attr { return markup.NewAttr("dir", v) }

// Download returns the download attribute.
func Download(v string) markup.Attr { return markup.NewAttr("download", v) }

// Enctype returns the enctype attribute.
func Enctype(v string) markup.Attr { return markup.NewAttr("enctype", v) }

// For returns the for attribute.
func For(v string) markup.Attr { return markup.NewAttr("for", v) }

// Form returns the form attribute.
func Form(v string) markup.Attr { return markup.NewAttr("form", v) }

// Height returns the height attribute.
func Height(v string) markup.Attr { return markup.NewAttr("height", v) }

// Hreflang returns the hreflang attribute.
func Hreflang(v string) markup.Attr { return markup.NewAttr("hreflang", v) }

// HTTPEquiv returns the http-equiv attribute.
func HTTPEquiv(v string) markup.Attr { return markup.NewAttr("http-equiv", v) }

// ID returns the id attribute.
func ID(v string) markup.Attr { return markup.NewAttr("id", v) }

// Integrity returns the integrity attribute.
func Integrity(v string) markup.Attr { return markup.NewAttr("integrity", v) }

// Lang returns the lang attribute.
func Lang(v string) markup.Attr { return markup.NewAttr("lang", v) }

// List returns the list attribute.
func List(v string) markup.Attr { return markup.NewAttr("list", v) }

// Loading returns the loading attribute.
func Loading(v string) markup.Attr { return markup.NewAttr("loading", v) }

// Max returns the max attribute.
func Max(v string) markup.Attr { return markup.NewAttr("max", v) }

// Maxlength returns the maxlength attribute.
func Maxlength(v string) markup.Attr { return markup.NewAttr("maxlength", v) }

// Method returns the method attribute.
func Method(v string) markup.Attr { return markup.NewAttr("method", v) }

// Min returns the min attribute.
func Min(v string) markup.Attr { return markup.NewAttr("min", v) }

// Minlength returns the minlength attribute.
func Minlength(v string) markup.Attr { return markup.NewAttr("minlength", v) }

// Name returns the name attribute.
func Name(v string) markup.Attr { return markup.NewAttr("name", v) }

// Pattern returns the pattern attribute.
func Pattern(v string) markup.Attr { return markup.NewAttr("pattern", v) }

// Placeholder returns the placeholder attribute.
func Placeholder(v string) markup.Attr { return markup.NewAttr("placeholder", v) }

// Referrerpolicy returns the referrerpolicy attribute.
func Referrerpolicy(v string) markup.Attr { return markup.NewAttr("referrerpolicy", v) }

// Rel returns the rel attribute.
func Rel(v string) markup.Attr { return markup.NewAttr("rel", v) }

// Role returns the role attribute.
func Role(v string) markup.Attr { return markup.NewAttr("role", v) }

// Rows returns the rows attribute.
func Rows(v string) markup.Attr { return markup.NewAttr("rows", v) }

// Rowspan returns the rowspan attribute.
func Rowspan(v string) markup.Attr { return markup.NewAttr("rowspan", v) }

// Sizes returns the sizes attribute.
func Sizes(v string) markup.Attr { return markup.NewAttr("sizes", v) }

// Srcset returns the srcset attribute.
func Srcset(v string) markup.Attr { return markup.NewAttr("srcset", v) }

// Step returns the step attribute.
func Step(v string) markup.Attr { return markup.NewAttr("step", v) }

// Style returns the style attribute.
func Style(v string) markup.Attr { return markup.NewAttr("style", v) }

// Tabindex returns the tabindex attribute.
func Tabindex(v string) markup.Attr { return markup.NewAttr("tabindex", v) }

// Target returns the target attribute.
func Target(v string) markup.Attr { return markup.NewAttr("target", v) }

// Title returns the title attribute.
func Title(v string) markup.Attr { return markup.NewAttr("title", v) }

// Type returns the type attribute.
func Type(v string) markup.Attr { return markup.NewAttr("type", v) }

// Value returns the value attribute.
func Value(v string) markup.Attr { return markup.NewAttr("value", v) }

// Width returns the width attribute.
func Width(v string) markup.Attr { return markup.NewAttr("width", v) }

// Action returns the action attribute. Unsafe URL schemes render as "#unsafe".
func Action(v string) markup.Attr { return markup.URL("action", v) }

// Cite returns the cite attribute. Unsafe URL schemes render as "#unsafe".
func Cite(v string) markup.Attr { return markup.URL("cite", v) }

// Formaction returns the formaction attribute. Unsafe URL schemes render as "#unsafe".
func Formaction(v string) markup.Attr { return markup.URL("formaction", v) }

// Href returns the href attribute. Unsafe URL schemes render as "#unsafe".
func Href(v string) markup.Attr { return markup.URL("href", v) }

// Poster returns the poster attribute. Unsafe URL schemes render as "#unsafe".
func Poster(v string) markup.Attr { return markup.URL("poster", v) }

// Src returns the src attribute. Unsafe URL schemes render as "#unsafe".
func Src(v string) markup.Attr { return markup.URL("src", v) }

// Async returns the boolean async attribute.
func Async() markup.Attr { return markup.Bool("async") }

// Autofocus returns the boolean autofocus attribute.
func Autofocus() markup.Attr { return markup.Bool("autofocus") }

// Checked returns the boolean checked attribute.
func Checked() markup.Attr { return markup.Bool("checked") }

// Defer returns the boolean defer attribute.
func Defer() markup.Attr { return markup.Bool("defer") }

// Disabled returns the boolean disabled attribute.
func Disabled() markup.Attr { return markup.Bool("disabled") }

// Hidden returns the boolean hidden attribute.
func Hidden() markup.Attr { return markup.Bool("hidden") }

// Multiple returns the boolean multiple attribute.
func Multiple() markup.Attr { return markup.Bool("multiple") }

// Novalidate returns the boolean novalidate attribute.
func Novalidate() markup.Attr { return markup.Bool("novalidate") }

// Open returns the boolean open attribute.
func Open() markup.Attr { return markup.Bool("open") }

// Readonly returns the boolean readonly attribute.
func Readonly() markup.Attr { return markup.Bool("readonly") }

// Required returns the boolean required attribute.
func Required() markup.Attr { return markup.Bool("required") }

// Selected returns the boolean selected attribute.
func Selected() markup.Attr { return markup.Bool("selected") }
