// Code generated by internal/gen; DO NOT EDIT.

package html

import "github.com/rrchelbi/markup"

// A returns a <a> element.
func A(items ...markup.Node) *markup.Element { return markup.Tag("a", items...) }

// Abbr returns a <abbr> element.
func Abbr(items ...markup.Node) *markup.Element { return markup.Tag("abbr", items...) }

// Address returns a <address> element.
func Address(items ...markup.Node) *markup.Element { return markup.Tag("address", items...) }

// Area returns a <area> element.
func Area(items ...markup.Node) *markup.Element { return markup.Tag("area", items...) }

// Article returns a <article> element.
func Article(items ...markup.Node) *markup.Element { return markup.Tag("article", items...) }

// Aside returns a <aside> element.
func Aside(items ...markup.Node) *markup.Element { return markup.Tag("aside", items...) }

// Audio returns a <audio> element.
func Audio(items ...markup.Node) *markup.Element { return markup.Tag("audio", items...) }

// B returns a <b> element.
func B(items ...markup.Node) *markup.Element { return markup.Tag("b", items...) }

// Base returns a <base> element.
func Base(items ...markup.Node) *markup.Element { return markup.Tag("base", items...) }

// Bdi returns a <bdi> element.
func Bdi(items ...markup.Node) *markup.Element { return markup.Tag("bdi", items...) }

// Bdo returns a <bdo> element.
func Bdo(items ...markup.Node) *markup.Element { return markup.Tag("bdo", items...) }

// Blockquote returns a <blockquote> element.
func Blockquote(items ...markup.Node) *markup.Element { return markup.Tag("blockquote", items...) }

// Body returns a <body> element.
func Body(items ...markup.Node) *markup.Element { return markup.Tag("body", items...) }

// Br returns a <br> element.
func Br(items ...markup.Node) *markup.Element { return markup.Tag("br", items...) }

// Button returns a <button> element.
func Button(items ...markup.Node) *markup.Element { return markup.Tag("button", items...) }

// Canvas returns a <canvas> element.
func Canvas(items ...markup.Node) *markup.Element { return markup.Tag("canvas", items...) }

// Caption returns a <caption> element.
func Caption(items ...markup.Node) *markup.Element { return markup.Tag("caption", items...) }

// Cite returns a <cite> element.
func Cite(items ...markup.Node) *markup.Element { return markup.Tag("cite", items...) }

// Code returns a <code> element.
func Code(items ...markup.Node) *markup.Element { return markup.Tag("code", items...) }

// Col returns a <col> element.
func Col(items ...markup.Node) *markup.Element { return markup.Tag("col", items...) }

// Colgroup returns a <colgroup> element.
func Colgroup(items ...markup.Node) *markup.Element { return markup.Tag("colgroup", items...) }

// Data returns a <data> element.
func Data(items ...markup.Node) *markup.Element { return markup.Tag("data", items...) }

// Datalist returns a <datalist> element.
func Datalist(items ...markup.Node) *markup.Element { return markup.Tag("datalist", items...) }

// Dd returns a <dd> element.
func Dd(items ...markup.Node) *markup.Element { return markup.Tag("dd", items...) }

// Del returns a <del> element.
func Del(items ...markup.Node) *markup.Element { return markup.Tag("del", items...) }

// Details returns a <details> element.
func Details(items ...markup.Node) *markup.Element { return markup.Tag("details", items...) }

// Dfn returns a <dfn> element.
func Dfn(items ...markup.Node) *markup.Element { return markup.Tag("dfn", items...) }

// Dialog returns a <dialog> element.
func Dialog(items ...markup.Node) *markup.Element { return markup.Tag("dialog", items...) }

// Div returns a <div> element.
func Div(items ...markup.Node) *markup.Element { return markup.Tag("div", items...) }

// Dl returns a <dl> element.
func Dl(items ...markup.Node) *markup.Element { return markup.Tag("dl", items...) }

// Dt returns a <dt> element.
func Dt(items ...markup.Node) *markup.Element { return markup.Tag("dt", items...) }

// Em returns a <em> element.
func Em(items ...markup.Node) *markup.Element { return markup.Tag("em", items...) }

// Embed returns a <embed> element.
func Embed(items ...markup.Node) *markup.Element { return markup.Tag("embed", items...) }

// Fieldset returns a <fieldset> element.
func Fieldset(items ...markup.Node) *markup.Element { return markup.Tag("fieldset", items...) }

// Figcaption returns a <figcaption> element.
func Figcaption(items ...markup.Node) *markup.Element { return markup.Tag("figcaption", items...) }

// Figure returns a <figure> element.
func Figure(items ...markup.Node) *markup.Element { return markup.Tag("figure", items...) }

// Footer returns a <footer> element.
func Footer(items ...markup.Node) *markup.Element { return markup.Tag("footer", items...) }

// Form returns a <form> element.
func Form(items ...markup.Node) *markup.Element { return markup.Tag("form", items...) }

// H1 returns a <h1> element.
func H1(items ...markup.Node) *markup.Element { return markup.Tag("h1", items...) }

// H2 returns a <h2> element.
func H2(items ...markup.Node) *markup.Element { return markup.Tag("h2", items...) }

// H3 returns a <h3> element.
func H3(items ...markup.Node) *markup.Element { return markup.Tag("h3", items...) }

// H4 returns a <h4> element.
func H4(items ...markup.Node) *markup.Element { return markup.Tag("h4", items...) }

// H5 returns a <h5> element.
func H5(items ...markup.Node) *markup.Element { return markup.Tag("h5", items...) }

// H6 returns a <h6> element.
func H6(items ...markup.Node) *markup.Element { return markup.Tag("h6", items...) }

// Head returns a <head> element.
func Head(items ...markup.Node) *markup.Element { return markup.Tag("head", items...) }

// Header returns a <header> element.
func Header(items ...markup.Node) *markup.Element { return markup.Tag("header", items...) }

// Hgroup returns a <hgroup> element.
func Hgroup(items ...markup.Node) *markup.Element { return markup.Tag("hgroup", items...) }

// Hr returns a <hr> element.
func Hr(items ...markup.Node) *markup.Element { return markup.Tag("hr", items...) }

// HTML returns a <html> element.
func HTML(items ...markup.Node) *markup.Element { return markup.Tag("html", items...) }

// I returns a <i> element.
func I(items ...markup.Node) *markup.Element { return markup.Tag("i", items...) }

// Iframe returns a <iframe> element.
func Iframe(items ...markup.Node) *markup.Element { return markup.Tag("iframe", items...) }

// Img returns a <img> element.
func Img(items ...markup.Node) *markup.Element { return markup.Tag("img", items...) }

// Input returns a <input> element.
func Input(items ...markup.Node) *markup.Element { return markup.Tag("input", items...) }

// Ins returns a <ins> element.
func Ins(items ...markup.Node) *markup.Element { return markup.Tag("ins", items...) }

// Kbd returns a <kbd> element.
func Kbd(items ...markup.Node) *markup.Element { return markup.Tag("kbd", items...) }

// Label returns a <label> element.
func Label(items ...markup.Node) *markup.Element { return markup.Tag("label", items...) }

// Legend returns a <legend> element.
func Legend(items ...markup.Node) *markup.Element { return markup.Tag("legend", items...) }

// Li returns a <li> element.
func Li(items ...markup.Node) *markup.Element { return markup.Tag("li", items...) }

// Link returns a <link> element.
func Link(items ...markup.Node) *markup.Element { return markup.Tag("link", items...) }

// Main returns a <main> element.
func Main(items ...markup.Node) *markup.Element { return markup.Tag("main", items...) }

// Map returns a <map> element.
func Map(items ...markup.Node) *markup.Element { return markup.Tag("map", items...) }

// Mark returns a <mark> element.
func Mark(items ...markup.Node) *markup.Element { return markup.Tag("mark", items...) }

// Menu returns a <menu> element.
func Menu(items ...markup.Node) *markup.Element { return markup.Tag("menu", items...) }

// Meta returns a <meta> element.
func Meta(items ...markup.Node) *markup.Element { return markup.Tag("meta", items...) }

// Meter returns a <meter> element.
func Meter(items ...markup.Node) *markup.Element { return markup.Tag("meter", items...) }

// Nav returns a <nav> element.
func Nav(items ...markup.Node) *markup.Element { return markup.Tag("nav", items...) }

// Noscript returns a <noscript> element.
func Noscript(items ...markup.Node) *markup.Element { return markup.Tag("noscript", items...) }

// Object returns a <object> element.
func Object(items ...markup.Node) *markup.Element { return markup.Tag("object", items...) }

// Ol returns a <ol> element.
func Ol(items ...markup.Node) *markup.Element { return markup.Tag("ol", items...) }

// Optgroup returns a <optgroup> element.
func Optgroup(items ...markup.Node) *markup.Element { return markup.Tag("optgroup", items...) }

// Option returns a <option> element.
func Option(items ...markup.Node) *markup.Element { return markup.Tag("option", items...) }

// Output returns a <output> element.
func Output(items ...markup.Node) *markup.Element { return markup.Tag("output", items...) }

// P returns a <p> element.
func P(items ...markup.Node) *markup.Element { return markup.Tag("p", items...) }

// Picture returns a <picture> element.
func Picture(items ...markup.Node) *markup.Element { return markup.Tag("picture", items...) }

// Pre returns a <pre> element.
func Pre(items ...markup.Node) *markup.Element { return markup.Tag("pre", items...) }

// Progress returns a <progress> element.
func Progress(items ...markup.Node) *markup.Element { return markup.Tag("progress", items...) }

// Q returns a <q> element.
func Q(items ...markup.Node) *markup.Element { return markup.Tag("q", items...) }

// Rp returns a <rp> element.
func Rp(items ...markup.Node) *markup.Element { return markup.Tag("rp", items...) }

// Rt returns a <rt> element.
func Rt(items ...markup.Node) *markup.Element { return markup.Tag("rt", items...) }

// Ruby returns a <ruby> element.
func Ruby(items ...markup.Node) *markup.Element { return markup.Tag("ruby", items...) }

// S returns a <s> element.
func S(items ...markup.Node) *markup.Element { return markup.Tag("s", items...) }

// Samp returns a <samp> element.
func Samp(items ...markup.Node) *markup.Element { return markup.Tag("samp", items...) }

// Script returns a <script> element.
func Script(items ...markup.Node) *markup.Element { return markup.Tag("script", items...) }

// Search returns a <search> element.
func Search(items ...markup.Node) *markup.Element { return markup.Tag("search", items...) }

// Section returns a <section> element.
func Section(items ...markup.Node) *markup.Element { return markup.Tag("section", items...) }

// Select returns a <select> element.
func Select(items ...markup.Node) *markup.Element { return markup.Tag("select", items...) }

// Slot returns a <slot> element.
func Slot(items ...markup.Node) *markup.Element { return markup.Tag("slot", items...) }

// Small returns a <small> element.
func Small(items ...markup.Node) *markup.Element { return markup.Tag("small", items...) }

// Source returns a <source> element.
func Source(items ...markup.Node) *markup.Element { return markup.Tag("source", items...) }

// Span returns a <span> element.
func Span(items ...markup.Node) *markup.Element { return markup.Tag("span", items...) }

// Strong returns a <strong> element.
func Strong(items ...markup.Node) *markup.Element { return markup.Tag("strong", items...) }

// Style returns a <style> element.
func Style(items ...markup.Node) *markup.Element { return markup.Tag("style", items...) }

// Sub returns a <sub> element.
func Sub(items ...markup.Node) *markup.Element { return markup.Tag("sub", items...) }

// Summary returns a <summary> element.
func Summary(items ...markup.Node) *markup.Element { return markup.Tag("summary", items...) }

// Sup returns a <sup> element.
func Sup(items ...markup.Node) *markup.Element { return markup.Tag("sup", items...) }

// Table returns a <table> element.
func Table(items ...markup.Node) *markup.Element { return markup.Tag("table", items...) }

// Tbody returns a <tbody> element.
func Tbody(items ...markup.Node) *markup.Element { return markup.Tag("tbody", items...) }

// Td returns a <td> element.
func Td(items ...markup.Node) *markup.Element { return markup.Tag("td", items...) }

// Template returns a <template> element.
func Template(items ...markup.Node) *markup.Element { return markup.Tag("template", items...) }

// Textarea returns a <textarea> element.
func Textarea(items ...markup.Node) *markup.Element { return markup.Tag("textarea", items...) }

// Tfoot returns a <tfoot> element.
func Tfoot(items ...markup.Node) *markup.Element { return markup.Tag("tfoot", items...) }

// Th returns a <th> element.
func Th(items ...markup.Node) *markup.Element { return markup.Tag("th", items...) }

// Thead returns a <thead> element.
func Thead(items ...markup.Node) *markup.Element { return markup.Tag("thead", items...) }

// Time returns a <time> element.
func Time(items ...markup.Node) *markup.Element { return markup.Tag("time", items...) }

// Title returns a <title> element.
func Title(items ...markup.Node) *markup.Element { return markup.Tag("title", items...) }

// Tr returns a <tr> element.
func Tr(items ...markup.Node) *markup.Element { return markup.Tag("tr", items...) }

// Track returns a <track> element.
func Track(items ...markup.Node) *markup.Element { return markup.Tag("track", items...) }

// U returns a <u> element.
func U(items ...markup.Node) *markup.Element { return markup.Tag("u", items...) }

// Ul returns a <ul> element.
func Ul(items ...markup.Node) *markup.Element { return markup.Tag("ul", items...) }

// Var returns a <var> element.
func Var(items ...markup.Node) *markup.Element { return markup.Tag("var", items...) }

// Video returns a <video> element.
func Video(items ...markup.Node) *markup.Element { return markup.Tag("video", items...) }

// Wbr returns a <wbr> element.
func Wbr(items ...markup.Node) *markup.Element { return markup.Tag("wbr", items...) }
